"""create initial tables

Revision ID: f02be848f6ee
Revises: 
Create Date: 2026-09-06 21:39:00.386267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f02be848f6ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_methods')),
    sa.UniqueConstraint('name', name=op.f('uq_delivery_methods_name'))
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('price>=0', name=op.f('ck_items_price_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('name', name=op.f('uq_items_name'))
    )
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_order_statuses_name'))
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_methods')),
    sa.UniqueConstraint('name', name=op.f('uq_payment_methods_name'))
    )
    op.create_table('persons',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("name = LOWER(TRIM(name)) AND name != '' AND name !~ '\\s{2,}'", name=op.f('ck_persons_name_normalized')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_persons')),
    sa.UniqueConstraint('name', name=op.f('uq_persons_name'))
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_code', sa.Text(), nullable=False),
    sa.Column('order_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delivery_date', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('buyer_id', sa.BigInteger(), nullable=True),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=25), nullable=False),
    sa.Column('buyer_address', sa.Text(), nullable=False),
    sa.Column('recipient_id', sa.BigInteger(), nullable=True),
    sa.Column('recipient_name', sa.String(length=255), nullable=False),
    sa.Column('recipient_phone', sa.String(length=25), nullable=False),
    sa.Column('recipient_address', sa.Text(), nullable=False),
    sa.Column('delivery_method_id', sa.Integer(), nullable=True),
    sa.Column('payment_method_id', sa.Integer(), nullable=True),
    sa.Column('order_status_id', sa.Integer(), nullable=True),
    sa.Column('shipping_cost', sa.BigInteger(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('delivery_date >= order_date', name=op.f('ck_orders_delivery_not_before_order')),
    sa.CheckConstraint('shipping_cost >= 0', name=op.f('ck_orders_shipping_cost_positive')),
    sa.ForeignKeyConstraint(['buyer_id'], ['persons.id'], name=op.f('fk_orders_buyer_id_persons')),
    sa.ForeignKeyConstraint(['delivery_method_id'], ['delivery_methods.id'], name=op.f('fk_orders_delivery_method_id_delivery_methods')),
    sa.ForeignKeyConstraint(['order_status_id'], ['order_statuses.id'], name=op.f('fk_orders_order_status_id_order_statuses')),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.id'], name=op.f('fk_orders_payment_method_id_payment_methods')),
    sa.ForeignKeyConstraint(['recipient_id'], ['persons.id'], name=op.f('fk_orders_recipient_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('person_addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("address != '' AND address = TRIM(address)", name=op.f('ck_person_addresses_address_no_stray_whitespace')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_addresses_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_addresses')),
    sa.UniqueConstraint('person_id', 'address', name=op.f('uq_person_addresses_person_id'))
    )
    op.create_table('person_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=25), nullable=False),
    sa.Column('person_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_phones_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_phones')),
    sa.UniqueConstraint('person_id', 'phone_number', name=op.f('uq_person_phones_person_id'))
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('item_price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('line_total', sa.BigInteger(), sa.Computed('quantity * item_price', ), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('item_price >= 0', name=op.f('ck_order_items_item_price_positive')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_minimum_one')),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_order_items_item_id_items')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.PrimaryKeyConstraint('order_id', 'item_id', name=op.f('pk_order_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('person_phones')
    op.drop_table('person_addresses')
    op.drop_table('orders')
    op.drop_table('persons')
    op.drop_table('payment_methods')
    op.drop_table('order_statuses')
    op.drop_table('items')
    op.drop_table('delivery_methods')
    # ### end Alembic commands ###
