"""merge_person_phones_into_persons

Revision ID: 392fde68ca8a
Revises: f02be848f6ee
Create Date: 2026-09-06 21:58:23.936347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392fde68ca8a'
down_revision: Union[str, Sequence[str], None] = 'f02be848f6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person_phones')
    op.add_column('persons', sa.Column('phone_number', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persons', 'phone_number')
    op.create_table('person_phones',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=25), autoincrement=False, nullable=False),
    sa.Column('person_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_person_phones_person_id_persons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person_phones')),
    sa.UniqueConstraint('person_id', 'phone_number', name=op.f('uq_person_phones_person_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
