"""add persons name constraints

Revision ID: 1d25ae298b5e
Revises: 887c8660b02a
Create Date: 2026-09-06 21:31:26.182649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d25ae298b5e'
down_revision: Union[str, Sequence[str], None] = '887c8660b02a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_persons_name'), 'persons', ['name'])
    op.create_check_constraint(op.f('ck_persons_name_normalized'), 'persons', "name = LOWER(TRIM(name)) AND name != '' AND name !~ '\\s{2,}'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_persons_name_normalized'), 'persons', type_='check')
    op.drop_constraint(op.f('uq_persons_name'), 'persons', type_='unique')
    # ### end Alembic commands ###
